# Generated by Django 5.0.6 on 2024-06-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='intventory',
            new_name='inventory',
        ),
    ]
